name: Laravel

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: root  
        ports:  
          - 3306:3306 
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -n --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: DB migrate
      run: php artisan migrate --seed
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SSH_HOST }}
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          username: ${{ secrets.TEST_SSH_USERNAME }}
          script: |
            cd /home/mark/Stone
            git pull
            cd /home/mark/laradock
            docker-compose exec -T workspace bash -c "cd Stone/ && composer update && php artisan migrate"
